---
- name: Deploy secrets env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ rustguac_prefix }}/env"
    owner: rustguac
    group: rustguac
    mode: "0600"
  notify: restart rustguac
  when: rustguac_oidc_client_secret | length > 0 or rustguac_vault_secret_id | length > 0
